elasticsearch:
  image: elasticsearch:1.5.2
  volumes:
    - /es/plugins:/usr/share/elasticsearch/plugins
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: kibana:4.0.3
  environment:
    - ELASTICSEARCH_URL=http://192.168.99.100:9200
  ports:
    - 5601:5601

fluentd-worker:
  build: fluentd-docker-image
  ports:
    - 24224:24224
  environment:
    - FLUENTD_CONF=/fluentd/conf/fluent-worker.conf

fluentd-aggregator:
  build: fluentd-docker-image
  ports:
    - 24225:24225
  environment:
    - FLUENTD_CONF=/fluentd/conf/fluent-aggregator.conf
    - EXPOSE=24225
