elasticsearch:
  image: elasticsearch:1.5.2
  volumes:
    - /es/plugins:/usr/share/elasticsearch/plugins
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: kibana:4.0.3
  environment:
    - ELASTICSEARCH_URL=http://192.168.99.100:9200
  ports:
    - 5601:5601

fluent:
  build: fluentd-docker-image
  ports:
    - 24224:24224
